# Generated by Django 3.2 on 2022-09-02 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
